version: '3.9'
services:
  web-check:
    container_name: Web-Check
    #image: lissy93/web-check
    build:
      context: ./
    image: wecantest/peek:latest
    ports:
      - 3000:3000
    restart: unless-stopped
